---
apiVersion: v1
kind: Pod
metadata: 
  name: fortunepod
  labels:
    version: v1
    name: fortunepod

spec:
  containers:
  - name: fortune-container
    image: secondspace/fortune:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000 