---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: wp-pvc
 labels:
   name: wp-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    name: wordpress-deploy
spec:
  selector:
    matchLabels:
      name: wordpresspod
  template:
    metadata:
      name: wordpresspod
      labels:
        name: wordpresspod
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef: 
            name: wp-secret
        - configMapRef:
            name: wp-cm

        ports:
        - name: wp-port
          containerPort: 80
        volumeMounts: 
        - name: wp-vol
          mountPath: /var/www/html

        resources: 
          requests:
            cpu: 100m
            memory: 32Mi
---
apiVersion: v1
kind: Service
metadata: 
  name: wordpress-service
  labels:
    name: wordpress-service
spec:
  type: ClusterIP
  selector: 
    name: wordpresspod
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpressins
  labels:
    name: wordpressins
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "30"
spec:
  ingressClassName: nginx
  rules:
  - host: wordpress.163.47.10.203.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: wordpress-service
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wp-netpol
  labels:
    name: wp-netpol
spec:
  podSelector: 
    matchLabels:
      name: wordpresspod
  policyTypes:
  - Ingress
  ingress:
  - from: 
  - namespaceSelector: 
      matchLabels: 
        name: wordpresspod
    ports:
    - port: 3306
      protocol: TCP