---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy

spec:
  replicas: 3
  selector:
    matchLabels:
      name: bggapppod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      name: bggapppod
      labels:
        name: bggapppod
    spec:
      containers:
      - name: bggapp-container
      # update the image
        image: chukmunnlee/bggapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000 
        envFrom:
        - configMapRef: 
            name: bgg-cm
        - secretRef: 
            name: bgg-secret

---
apiVersion: v1
kind: Service
metadata: 
  name: bggapp-service
  labels:
    name: bggapp-service
spec:
  type: LoadBalancer 
  selector: 
    name: bggapppod
  ports:
  - port: 80
    targetPort: 3000